Milestone two
joomla-projects/gsoc18_cli_update pull request #11
Opened 2018-06-07 08:10 UTC by bosunski

Pull Request for Issue #7  .

### Summary of Changes

Added Commands for Extension install, list and remove
`php cli/joomla.php extension:list`

`php cli/joomla.php extension:remove <extension_id>`

`php cli/joomla.php extension:install path --path=<path_to_extension>`

`php cli/joomla.php extension:install url --url=<url_to_extension>`

2018-06-09 05:51 UTC, alikon commented
for the command `php cli/joomla.php extension:list`
would be nice to add a "Version" column to report the extension version too

![screenshot from 2018-06-09 07-50-06](https://user-images.githubusercontent.com/181681/41188145-c21234ce-6bb9-11e8-951e-64a8dd723d22.png)

2018-06-09 05:56 UTC, alikon commented
for the command `php cli/joomla.php extension:list` we need to add a parameter `--type`

something like : 
 
`php cli/joomla.php extension:list --type=plugin`

or

`php cli/joomla.php extension:list --type=template`

etc

2018-06-09 06:27 UTC, alikon requested changes

2018-06-09 06:27 UTC, alikon commented on libraries/src/Console/ExtensionRemoveCommand.php
> +		$installer = \JInstaller::getInstance();
please use namespaced for : 
`\JInstaller::getInstance();`

` \JTable::getInstance('extension');`

2018-06-09 06:35 UTC, alikon commented
for the command `php cli/joomla.php extension:remove <extension_id>`

we need to check the existence of the extension before to ask are you sure to remove 
in this screenshot i've issued a command to remove a non existent extension **10001**
![screenshot from 2018-06-09 08-33-37](https://user-images.githubusercontent.com/181681/41188574-d3bea134-6bbf-11e8-8d01-dfe200621070.png)

2018-06-09 07:05 UTC, bosunski commented
Alright @alikon I will start work on all reviews

2018-06-09 07:28 UTC, alikon commented
trying to remove an existing extension **10000**

![screenshot from 2018-06-09 09-26-57](https://user-images.githubusercontent.com/181681/41188975-53b825f2-6bc7-11e8-99f8-317f9ba4d79e.png)

2018-06-09 08:35 UTC, alikon commented
i've installed com_patchtester from the web app when i try to remove it form CLI i've got a  PHP warning

> Use of undefined constant JOOMLA_MINIMUM_PHP

![screenshot from 2018-06-09 10-08-45](https://user-images.githubusercontent.com/181681/41189578-627b6c94-6bd0-11e8-8610-7539fec241cf.png)

to fix this i've defined that constant like this

```
 /**
 * Define the application's minimum supported PHP version as a constant so it can be referenced within the application.
 */
define('JOOMLA_MINIMUM_PHP', '7.0');

```

2018-06-09 08:37 UTC, bosunski commented
Cool @alikon :+1: Worked like a charm!!

2018-06-09 08:38 UTC, bosunski commented
But where would you think will be a good place to define that constant?

2018-06-09 08:44 UTC, alikon commented
in https://github.com/joomla-projects/gsoc18_cli_update/blob/master/libraries/src/Application/ConsoleApplication.php

2018-06-09 08:48 UTC, bosunski commented
I'm thinking `cli/joomla.php` will be fine, that's the main entry script

2018-06-09 09:36 UTC, alikon commented
just a small one
`php cli/joomla.php extension:list --help
`

should inform that you can use a command syntax like this

`php cli/joomla.php extension:list --type=package`

2018-06-10 05:23 UTC, alikon approved these changes

2018-06-10 18:52 UTC, rjcf18 approved these changes
Code seems fine, I tested and everything works as expected afaic

2018-06-11 15:40 UTC, HLeithner requested changes
Please check you code style, its a bit flaky

2018-06-11 15:40 UTC, HLeithner commented on libraries/src/Application/ConsoleApplication.php
> +		return $config->get($key);
Is there a reason for defining the $config variable?

2018-06-11 15:40 UTC, HLeithner commented on libraries/src/Console/ExtensionInstallCommand.php
> +			$result = $this->processPathInstallation($this->cliInput->getOption('path'));
missing new line after

2018-06-11 15:40 UTC, HLeithner commented on libraries/src/Console/ExtensionInstallCommand.php
> +		if (!in_array($from, ['path', 'url']))
is there a reason you do this check twice? I would remove this here and keep the final else on line 99

2018-06-11 15:40 UTC, HLeithner commented on libraries/src/Console/ExtensionRemoveCommand.php
> +		if ($response == 'yes')
should have 3 =

2018-06-11 15:40 UTC, HLeithner commented on libraries/src/Console/ExtensionRemoveCommand.php
> +		elseif ($response == 'no')
should have 3 =

2018-06-11 15:40 UTC, HLeithner commented on libraries/src/Console/ExtensionRemoveCommand.php
> +		$response = $this->ioStyle->ask('Are you sure you want to remove this extension?', 'yes/no');
maybe strtolower case the input

2018-06-11 15:40 UTC, HLeithner commented on libraries/src/Console/ExtensionRemoveCommand.php
> +		else
make no sense in my opinion, I would remove $response === 'no' and let the output say something like 'Abort uninstalling extension'

2018-06-11 15:40 UTC, HLeithner commented on libraries/src/Console/ExtensionRemoveCommand.php
> +					$this->ioStyle->success('Extension Removed!');
I would lowercase 'removed'

2018-06-11 15:40 UTC, HLeithner commented on libraries/src/Console/ExtensionRemoveCommand.php
> +			$this->ioStyle->note('Extension Not Removed.');
I would lowercase 'not' and 'removed'

2018-06-11 15:40 UTC, HLeithner commented on libraries/src/Console/ExtensionRemoveCommand.php
> +		$this->setDescription('Removes an Extension');
I would lowercase 'Extension'

2018-06-11 15:40 UTC, HLeithner commented on libraries/src/Console/ExtensionsListCommand.php
> +		$extensions = $db->loadAssocList('extension_id');
blank line after this would be nice

2018-06-11 15:40 UTC, HLeithner commented on libraries/src/Console/ExtensionsListCommand.php
> +		}
blank line required after } iirc

2018-06-11 15:44 UTC, mbabker commented on libraries/src/Application/ConsoleApplication.php
> +		return $config->get($key);
Actually, what do you even need this `getCfg` method for to begin with?  We've deprecated `Factory::getConfig()` in favor of `Factory::getApplication()->get($key);`, so within the class context it would just be `$this->get($key);`.  No need for a new method.

2018-06-12 19:45 UTC, bosunski commented on libraries/src/Application/ConsoleApplication.php
> +		return $config->get($key);
@mbabker @HLeithner I tried this `$this->get($key)` within the command class, I got this back: `                                                                            
  [Symfony\Component\Debug\Exception\FatalThrowableError]                     
  Call to undefined method Joomla\CMS\Console\ExtensionInstallCommand::get() `

2018-06-14 11:48 UTC, bosunski commented on libraries/src/Application/ConsoleApplication.php
> +		return $config->get($key);
@mbabker I still can't resolve this

2018-06-14 12:00 UTC, mbabker commented on libraries/src/Application/ConsoleApplication.php
> +		return $config->get($key);
There isn't a `get()` method on the command class.  You'd need to do `$this->getApplication()->get()`.

2018-06-14 12:08 UTC, bosunski commented on libraries/src/Application/ConsoleApplication.php
> +		return $config->get($key);
okay I will try that

2018-06-15 06:29 UTC, bosunski commented
@HLeithner all review is now adjusted.

2018-06-18 20:25 UTC, merged