Milestone one
joomla-projects/gsoc18_cli_update pull request #12
Opened 2018-06-07 11:10 UTC by bosunski

Pull Request for Issue #4   .

### Summary of Changes
Added the Command Class

### Testing Instructions
Run php cli/joomla.php check-updates

### Expected result

Tells whether there is a new update or not.

### Actual result
` ! [NOTE] New Joomla Version 4.0.0-alpha4-dev is available.`

OR 

`[OK] You already have the latest Joomla version 4.0.0-alpha4-dev`

2018-06-07 18:09 UTC, alikon commented
still the same as before we are not reporting the same info as the web app if the download url is unreachable
![screenshot from 2018-06-07 20-06-45](https://user-images.githubusercontent.com/181681/41117862-80024bb8-6a8e-11e8-9334-33376829af0f.png)


look at this code please https://github.com/joomla-projects/gsoc18_cli_update/blob/6ee625f0b7d684f985cf4aab91ad595c887a0d60/administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_nodownload.php#L31

2018-06-07 18:10 UTC, alikon requested changes
we need to report if the download url is not reachable as the web app do

2018-06-09 05:13 UTC, alikon commented
please don't blindly c&p code, test on your side before, please 

https://github.com/bosunski/gsoc18_cli_update/blob/fe8d341236e14433fe62d69890d612330b741fed/libraries/src/Console/CheckJoomlaUpdatesCommand.php#L44-L61

should be something  like 
```php
		if (!$data['hasUpdate'])
		{
			$symfonyStyle->success('You already have the latest Joomla version ' . $data['latest']);

			return 0;
		}

		$symfonyStyle->note('New Joomla Version ' . $data['latest'] . ' is available.');

		if (!isset($data['object']->downloadurl->_data))
		{
			$symfonyStyle->warning('We cannot find an update URL ');
		}

		return 0;
```

that produce 

![screenshot from 2018-06-09 07-11-53](https://user-images.githubusercontent.com/181681/41187898-79fc0f8e-6bb4-11e8-93f3-6abbce49bf78.png)

2018-06-09 05:18 UTC, bosunski commented
Most likely I didn't get your intent from the start.

2018-06-09 07:04 UTC, alikon approved these changes

2018-06-09 07:07 UTC, alikon commented
i'm asking a final review from all @mentors after is ready to be merged

2018-06-09 07:52 UTC, alikon commented
@rjcf18
@HLeithner
@nibra 
@mdings

2018-06-10 13:42 UTC, bosunski commented
Ok @alikon

2018-06-10 14:05 UTC, HLeithner requested changes
Please use JText for text strings.

2018-06-10 14:05 UTC, HLeithner commented on libraries/src/Console/CheckJoomlaUpdatesCommand.php
> +			$symfonyStyle->success('You already have the latest Joomla version ' . $data['latest']);
JText::_('CLI_UPDATE_....')

2018-06-10 14:05 UTC, HLeithner commented on libraries/src/Console/CheckJoomlaUpdatesCommand.php
> +			$symfonyStyle->note('New Joomla Version ' . $data['latest'] . ' is available.');
```JText::sprintf('CLI_UPDATE_NEW_VERSION_AVAILABLE', $data['latest']);```
ini:
```CLI_UPDATE_NEW_VERSION_AVAILABLE="New Joomla Version %s is available."```

2018-06-10 14:05 UTC, HLeithner commented on libraries/src/Console/CheckJoomlaUpdatesCommand.php
> +			$symfonyStyle->warning('We cannot find an update URL ');
JText::_('CLI_UPDATE_...');

2018-06-10 14:05 UTC, HLeithner commented on libraries/src/Console/CheckJoomlaUpdatesCommand.php
> +		$this->setDescription('Checks for Joomla updates');
JText::_('CLI_UPDATE_...');

2018-06-10 14:05 UTC, HLeithner commented on libraries/src/Console/CheckJoomlaUpdatesCommand.php
> +		$this->setHelp($help);
Why do we have a $help variable here?

if we need %command.name% here because of the symfony framework but it in the language file anyway

2018-06-10 16:56 UTC, HLeithner commented
As mentioned in the last meeting report you should add the translation thing. 

https://volunteers.joomla.org/teams/gsoc-18-command-line-update/reports/819-mentors-student-meeting-18-06-14

> Reporting on MS1 Student informed that he thought he was ready and that LANGUAGE strings were not extremely important. That however was a misunderstanding and these should be taken care of in the comming week

2018-06-10 17:36 UTC, mbabker commented
I'm not opposed to having the CLI interface translated.  But, I don't think it's within the scope of this particular GSoC project to decide how the core Joomla CLI interface deals with translations.  There are other considerations to be made beyond copying the text into an INI file, loading said INI file, and use of the `JText` class API; it's an architectural discussion that IMO is secondary to what this project's goal is.  If you have time at the end of the project period to work on it then by all means do so.

2018-06-10 18:48 UTC, bosunski commented
@HLeithner I knew it was requested and I did implemented it. After i implemented the language thing, micheal commented and then I had to remove the Language awareness Implementation again because I was recommended on GLIP to do so, if the code will get merged to the core. Refer to the Quotes i made on glip.

2018-06-10 18:50 UTC, rjcf18 approved these changes
Everything seems ok now afaic

2018-06-10 19:13 UTC, HLeithner approved these changes
ok so it ok for me too thx @mbabker for clarification

2018-06-18 20:23 UTC, merged