Created test and command for joomla check-updates
joomla-projects/gsoc18_cli_update pull request #6
Opened 2018-05-25 13:27 UTC by bosunski

Pull Request for Issue #4   .

### Summary of Changes
Added the Command Class

### Testing Instructions
Run php cli/joomla.php check-update

### Expected result

Tells whether there is a new update or not.

### Actual result
` ! [NOTE] New Joomla Version 4.0.0-alpha4-dev is available.`

OR 

`[OK] You already have the latest Joomla version 4.0.0-alpha4-dev`

2018-05-28 18:10 UTC, alikon commented on libraries/src/Console/CheckJoomlaUpdatesCommand.php
> +			<<<EOF
is there a better way than <<<EOF

2018-05-28 18:14 UTC, HLeithner commented on libraries/src/Console/CheckJoomlaUpdatesCommand.php
> +			<<<EOF
Shouldn't this be translate able?

2018-05-28 18:15 UTC, mbabker commented on libraries/src/Console/CheckJoomlaUpdatesCommand.php
> +			<<<EOF
> is there a better way than <<<EOF

What's wrong with HEREDOC syntax?

> Shouldn't this be translate able?

Command line stuff isn't easy to handle translations in.  Sure we can make all the help contents and descriptions for commands translatable, but is the effort really worth it?

2018-05-28 18:18 UTC, HLeithner commented on tests/system/suites/console/CacheCleanTest.php
> +		$result = `php cli/joomla.php cache:clean`;
You should use exec() instead of backticks

2018-05-28 18:19 UTC, alikon commented on libraries/src/Console/CheckJoomlaUpdatesCommand.php
> +		$app = \JFactory::getApplication();
should'nt be namespaced Factory instead?

2018-05-28 18:19 UTC, alikon commented on libraries/src/Console/CheckJoomlaUpdatesCommand.php
> +			<<<EOF
HEREDOC only my personal taste ;)

2018-05-28 18:20 UTC, alikon commented on libraries/src/Console/CheckJoomlaUpdatesCommand.php
> +			<<<EOF
translatable, hmm nice to have

2018-05-28 19:51 UTC, bosunski commented
Ok. Noted all reviews. I will revamp and send back for review.

2018-05-28 19:52 UTC, bosunski commented on tests/system/suites/console/CacheCleanTest.php
> +		$result = `php cli/joomla.php cache:clean`;
I don't understand the return code part @HLeithner

2018-05-28 20:03 UTC, HLeithner commented on tests/system/suites/console/CacheCleanTest.php
> +		$result = `php cli/joomla.php cache:clean`;
php cli/joomla.php cache:clean should normally return a return code 0 if every thing was ok.

if an error occur the return code should be > 0.

so it should be possible for you to write something like
```php
exec('php cli/joomla.php cache:clean', $output, $ret);
$this->assertEquals($ret, 0, 'Checking of return code 0');
```

if the function and the joomla cli is written correctly it return 0 on success and not 0 if it was not success full

2018-05-28 20:16 UTC, bosunski commented on tests/system/suites/console/CacheCleanTest.php
> +		$result = `php cli/joomla.php cache:clean`;
Wow! Great! Didn't know I could do something like that. Very nice way for some tests.

2018-05-28 22:33 UTC, bosunski commented on libraries/src/Console/CheckJoomlaUpdatesCommand.php
> +		$app = \JFactory::getApplication();
Uuuuhmmm, whaich namespace is that? @alikon

2018-05-29 00:30 UTC, bosunski commented on libraries/src/Console/CheckJoomlaUpdatesCommand.php
> +		$app = \JFactory::getApplication();
No worries, I just found it.

2018-05-31 17:55 UTC, alikon commented
you need to take a look at https://github.com/joomla/joomla-cms/issues/20612

2018-06-01 00:48 UTC, nibra commented on tests/system/suites/console/CacheCleanTest.php
> +		$result = `php cli/joomla.php cache:clean`;
Actually, `shell_exec()` should be used. The backticks are too invisible. But you have to blame *me* for the backticks :)

2018-06-04 18:19 UTC, rjcf18 approved these changes

2018-06-04 21:41 UTC, rjcf18 approved these changes
Tested the command and it seems to be working fine.

2018-06-04 21:57 UTC, bosunski commented
@rjcf18 All tests passed now.

2018-06-04 22:05 UTC, bosunski commented on language/en-GB/en-GB.check_updates_cli.ini
> +CHECK_UPDATES_HELP="The <info>%command.name%</info> Checks for Joomla updates.\n Usage: <info>php %command.full_name%</info>"
I brought the content of the HEREDOC(EOF) here and we don't have it in the command class anymore.

2018-06-04 22:18 UTC, mbabker commented on libraries/src/Console/CheckJoomlaUpdatesCommand.php
> +		$language = Factory::getLanguage();
The web interface has options for the user to set their preferred language, as is this basically hardcodes the language to only use whatever is set as the global default.  If we're really going to consider having the output of CLI commands translated, this needs to be discussed in an RFC on the main project repo; IMO this is out of scope for any of the GSoC projects to decide and implement on their own.

2018-06-04 23:45 UTC, bosunski commented on libraries/src/Console/CheckJoomlaUpdatesCommand.php
> +		$language = Factory::getLanguage();
Alright @mbabker 
I have reverted the changes.

2018-06-06 08:35 UTC, alikon commented
`tests/system/suites/console/CacheCleanTest.php`  it's outside the scope of this pr and should be moved on 4.0 main repo  same as #8

2018-06-07 06:17 UTC, alikon commented
i've tested 2 scenario (with some  dirty hack to downgrade the current version to simulate an update):

- there is no update
- there is an update
![screenshot from 2018-06-07 08-14-26](https://user-images.githubusercontent.com/181681/41081356-d9762ec6-6a2a-11e8-8df9-c364d90574e6.png)


did we should care about giving more info in the scenario that We can't find a download URL like in the web app ?

![screenshot from 2018-06-07 08-16-34](https://user-images.githubusercontent.com/181681/41081433-2016e4f6-6a2b-11e8-9807-713c8d4b0741.png)

2018-06-07 06:26 UTC, alikon requested changes
need to clean pr file tests/system/suites/console/CacheCleanTest.php for example 1 pr 1 task

2018-06-23 04:52 UTC, closed without merging